name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Start PHP Built-in Server
      run: nohup php -S 0.0.0.0:8000 -t . > /dev/null 2>&1 &
      
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo cp /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Run Pytest in Parallel
      run: |
        pytest -n auto
