name: CI/CD Pipeline for Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      run: |
        sudo apt-get update
        sudo apt-get install php-cli php-mysql -y

    - name: Start PHP Built-in Server
      run: |
        nohup php -S 127.0.0.1:8000 -t . > /dev/null 2>&1 &
        sleep 5

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest pytest-xdist

    - name: Run Integration Tests in Parallel
      run: pytest -n 5
